### ISSUE TITLE
[RFC] Deployment on Debian Bullseye may interference with update service and its timer

### ISSUE THREAD

**Issue by rtib** [rtib/puppet-geoip#41]
Debian [geoipupdate package](https://tracker.debian.org/pkg/geoipupdate) starting with Bullseye (debian-11) does contain a systemd service and a weekly timer to run geoipupdate. This may interference with the update timer deployed by this module.

Current options:

1. the module documentation becomes a warning on that and sysadmins have to deal with it on their end
2. the deployment of systemd service and timer gets disabled for Debian Bullseye in this module
3. the module takes over the control of the service and timer, i.e. default value of `geoip::service_name` is changed
 
Request for comments on how the module should deal with that.

**Comment by rtib** [comment]
@saz , @smortex @treydock I'd appreciate your opinion.

**Comment by saz** [comment]
I'd go with option 2

**Comment by rtib** [comment]
> I'd go with option 2

that would mean, that control over the scheduling of updates should be solved outside this module

**Comment by treydock** [comment]
I think option 2 but add a new parameter of `manage_service` that for every OS defaults to `true` in Hiera data but for Debian 11 it defaults to `false`.  This way if a site does want the Puppet module to overwrite the OS units, they can opt-in to that behavior.  I think that might require the `service_name` in Hiera data to also be different for Debian 11 if in fact the service name differs just so that if `manage_service => true` on Debian 11, it overwrites the OS units.

**Comment by rtib** [comment]
We already have [manage_service](https://github.com/rtib/puppet-geoip/blob/12c06f5f70aadf47f965436eb982f03010a46ca3/manifests/init.pp#L46) parameter, defaulting `true`, as well as [service_name](https://github.com/rtib/puppet-geoip/blob/12c06f5f70aadf47f965436eb982f03010a46ca3/manifests/init.pp#L50) parameter, defaulting `geoip_update`.

So how about setting default values for Debian-11 to:

- `manage_service: false`
- `service_name: geoipupdate` to meet Debian naming for the case, manage_service is turned intentionally on.

**Comment by smortex** [comment]
Toggling the default for the new Debian version looks reasonable.

Another option is to force-disable the packaged timer on Debian 11 and do not touch the rest, so that the behavior is the same on all operating systems.

This is typically the moment where you choose if applying the same catalog on two different nodes produce different configuration or if you want the module to be more "authoritative" :smiley: .  I am personally fine with both.

**Comment by rtib** [comment]
Choosing between break the behaviour of module or breaking the package installation isn't really what I'm happy with. So, I was puzzling around a bit and came up with #42 to allow the module implement the same manifest in all different environments without breaking the installation of distribution packages.
